name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type (major | minor | patch | premajor | preminor | prepatch | prerelease)'
        required: true
        default: 'prerelease'
        type: choice
        options:
        - prerelease
        - prepatch
        - preminor
        - premajor
        - patch
        - minor
        - major
      pre_id:
        description: 'Pre-release identifier (only used for pre* version types)'
        required: false
        default: 'rc'
        type: choice
        options:
        - rc
        - alpha
        - beta
        - experimental

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.3.5"

      - name: Configure Git User
        run: |
          git config user.email "19784671+shubhamomar@users.noreply.github.com"

      - name: Create .npmrc config
        working-directory: ./node
        run: |
          echo "release=${{ inputs.version_type }}" > .npmrc
          echo "preid=${{ inputs.pre_id }}" >> .npmrc

      - name: Bump Version & Sync
        working-directory: ./node
        run: bun run release

      - name: Push Changes
        run: git push --follow-tags
